name: Spice Grinder Repository Scanner

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'GitHub repo URL (e.g. https://github.com/org/repo.git)'
        required: false
        type: string

      file_path:
        description: 'Path on the runner to scan (e.g. /path/to/code)'
        required: false
        type: string

      branch:
        description: 'Branch to scan (only applies to URL)'
        required: false
        default: 'main'
        type: string

      config:
        description: 'Grinder config (e.g. adg, full)'
        required: true
        default: 'adg'
        type: string

      mode:
        description: 'Upload mode (e.g. gr, full)'
        required: true
        default: 'gr'
        type: string

  pull_request:  
    branches: ["main"]  

permissions:
  contents: read
  packages: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected inputs
        run: |
          echo "GitHub repo URL:    ${{ inputs.repository_url }}"
          echo "Custom file path:   ${{ inputs.file_path }}"
          echo "Branch:             ${{ inputs.branch }}"
          echo "Config:             ${{ inputs.config }}"
          echo "Mode:               ${{ inputs.mode }}"

      - name: Validate inputs (only one source allowed)
        run: |
          count=0
          [[ -n "${{ inputs.repository_url }}" ]] && ((count++))
          [[ -n "${{ inputs.file_path }}" ]] && ((count++))

          if [ "$count" -eq 0 ]; then
            echo "❌ ERROR: Please provide either 'repository_url' or 'file_path'."
            exit 1
          elif [ "$count" -gt 1 ]; then
            echo "❌ ERROR: Only one of 'repository_url' or 'file_path' can be used at a time."
            exit 1
          fi

      - name: Prepare input/output directories
        run: mkdir -p target/input target/output

      - name: Clone from URL
        if: ${{ inputs.repository_url != '' }}
        run: |
          git clone --branch ${{ inputs.branch }} --depth 1 ${{ inputs.repository_url }} target/input

      - name: Copy input from path
        if: ${{ inputs.file_path != '' }}
        run: |
          cp -r ${{ inputs.file_path }}/* target/input/

      - name: Scan with Spice Grinder
        run: |
          docker run --platform linux/amd64 --quiet --rm --network none --user $(id -u):$(id -g) \
          -v $(pwd)/target/input:/input:ro -v $(pwd)/target/output:/output spicelabs/grinder:latest \
          -c ${{ inputs.config }} -b /input -o /output

      - name: Upload with Spice Grinder
        run: |
          docker run --platform linux/amd64 --quiet --rm --user $(id -u):$(id -g) \
          -v $(pwd)/target/output:/output spicelabs/grinder:latest \
          -c upload -p /output \
          -j ${{ secrets.GRINDER_JWT }} \
          -m ${{ inputs.mode }}
